// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyaWvwqcknDHui0AGuDsHiSbPK65fI19g',
    appId: '1:977541553895:web:279de26b48501476060c42',
    messagingSenderId: '977541553895',
    projectId: 'fir-p-d8453',
    authDomain: 'fir-p-d8453.firebaseapp.com',
    storageBucket: 'fir-p-d8453.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8h1Dd1djm0Dl9AwgUF-HW_Tyo8GESX3k',
    appId: '1:977541553895:android:c3c80cf827f377fa060c42',
    messagingSenderId: '977541553895',
    projectId: 'fir-p-d8453',
    storageBucket: 'fir-p-d8453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXqr57HMRbiWM7PcopYv9toMntChXwUY',
    appId: '1:977541553895:ios:ac0c75ba1f3817b9060c42',
    messagingSenderId: '977541553895',
    projectId: 'fir-p-d8453',
    storageBucket: 'fir-p-d8453.firebasestorage.app',
    androidClientId: '977541553895-hsop1n8tuuvg8s0bva401v2fln1qluss.apps.googleusercontent.com',
    iosClientId: '977541553895-upv9sl2bfdj497lgmd4i3dqb1iqgd0jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.machineTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBXqr57HMRbiWM7PcopYv9toMntChXwUY',
    appId: '1:977541553895:ios:ac0c75ba1f3817b9060c42',
    messagingSenderId: '977541553895',
    projectId: 'fir-p-d8453',
    storageBucket: 'fir-p-d8453.firebasestorage.app',
    androidClientId: '977541553895-hsop1n8tuuvg8s0bva401v2fln1qluss.apps.googleusercontent.com',
    iosClientId: '977541553895-upv9sl2bfdj497lgmd4i3dqb1iqgd0jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.machineTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyaWvwqcknDHui0AGuDsHiSbPK65fI19g',
    appId: '1:977541553895:web:2570861b28fc3f4d060c42',
    messagingSenderId: '977541553895',
    projectId: 'fir-p-d8453',
    authDomain: 'fir-p-d8453.firebaseapp.com',
    storageBucket: 'fir-p-d8453.firebasestorage.app',
  );
}
